// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Kb-OVh3uQPSyYzpf7QaF2vywXALSEm0',
    appId: '1:554569980306:web:b23c7a8404ea153899094b',
    messagingSenderId: '554569980306',
    projectId: 'hackathon-54600',
    authDomain: 'hackathon-54600.firebaseapp.com',
    databaseURL: 'https://hackathon-54600-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-54600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWLxe0yIl0RIKsJ3roWK891Gra4G9ehI',
    appId: '1:554569980306:android:1582e787370d969e99094b',
    messagingSenderId: '554569980306',
    projectId: 'hackathon-54600',
    databaseURL: 'https://hackathon-54600-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-54600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd0Y9rQzAlH-V7Ww-r8supIJONIQlxyto',
    appId: '1:554569980306:ios:27b06fab4ac2945899094b',
    messagingSenderId: '554569980306',
    projectId: 'hackathon-54600',
    databaseURL: 'https://hackathon-54600-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-54600.appspot.com',
    iosClientId: '554569980306-ot8db6rnu8gstbmsm2k4bq5qqigu9t85.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd0Y9rQzAlH-V7Ww-r8supIJONIQlxyto',
    appId: '1:554569980306:ios:27b06fab4ac2945899094b',
    messagingSenderId: '554569980306',
    projectId: 'hackathon-54600',
    databaseURL: 'https://hackathon-54600-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-54600.appspot.com',
    iosClientId: '554569980306-ot8db6rnu8gstbmsm2k4bq5qqigu9t85.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
